name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  push:
    branches:
      - master
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
            docker buildx build --push \
            --tag saikpr/gpt-researcher:latest \
            --platform linux/amd64,linux/arm64 .